spring:
  application:
    name: service-order
  profiles:
    active: test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #namespace: 80546bd9-4745-417d-bc0e-1f60bdafb008
        namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        #namespace: 80546bd9-4745-417d-bc0e-1f60bdafb008
        namespace: 5d5d91ba-a655-497c-bbe5-f7fe9424a6ac
        prefix: server-order
        file-extension: yml
        # 禁用import check避免不必要的警告
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          # 使用于所有的feignClient的默认配置
          default:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: full
#            request-interceptors: 添加自定义请求拦截器方式一
#              - com.niici.order.interceptor.TokenRequestInterceptor
          # 自定义feignClient调用的超时时间
          service-product:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: full


server:
  port: 8001

# 配置日志级别 -- 需要配置成debug
logging:
  level:
    com.niici.order: debug

# 开启feign的sentinel支持
feign:
  sentinel:
    enabled: true
